### ISSUE TITLE
doesn't work with rustic

### ISSUE THREAD

**Issue by p00f** [meain/evil-textobj-tree-sitter#105]
I'm using (according to [this comment](https://github.com/brotzeit/rustic/pull/527#issuecomment-1728508812))
 - rust-mode: https://github.com/rust-lang/rust-mode/pull/482 rebased on master
 - rustic: master
 - evil-textobj-tree-sitter

However, this doesn't work for evil-textobj-tree-sitter. This change works, not sure if this is ideal:

```diff
diff --git a/evil-textobj-tree-sitter-core.el b/evil-textobj-tree-sitter-core.el
index 818e99a..0ab321a 100644
--- a/evil-textobj-tree-sitter-core.el
+++ b/evil-textobj-tree-sitter-core.el
@@ -61,7 +61,8 @@
 (defun evil-textobj-tree-sitter--use-builtin-treesitter ()
   "Return non-nil if we should use builtin treesitter."
   (and evil-textobj-tree-sitter--can-use-builtin-treesit
-       (string-suffix-p "-ts-mode" (symbol-name major-mode))))
+       (or (string= "rustic-mode" (symbol-name major-mode))
+           (string-suffix-p "-ts-mode" (symbol-name major-mode)))))
 
 (defun evil-textobj-tree-sitter--get-queries-dir ()
   "Get the queries directory.
```

**Comment by meain** [comment]
This should work for your current usecase, but I don't want to include this upstream until either of these(https://github.com/rust-lang/rust-mode/pull/482 or https://github.com/brotzeit/rustic/pull/527) is merged into master. Both use different way to switch to between `elisp-tree-sitter` and builtin `treesit`. The [first one](https://github.com/rust-lang/rust-mode/pull/482) uses `rust-mode-treesitter-derive` to switch and the [second one](https://github.com/brotzeit/rustic/pull/527) introduces a new mode `rustic-ts-mode`.

**Comment by p00f** [comment]
Understood, thanks!
