### ISSUE TITLE
loop and conditional textobjects

### ISSUE THREAD

**Issue by p00f** [meain/evil-textobj-tree-sitter#106]
helix doesn't have loop and conditional textobjects at all, would you object to me adding some of them here directly?

**Comment by meain** [comment]
Feel free to do so. I think I'll end up splitting the ones we import from helix and ones we add into separate files later to make it easier to maintain, but for now, you can add them to the end of the respective files.

**Comment by p00f** [comment]
I don't understand how it works in C++ though - neither C++ nor C (which C++ inherits from) have those textobjects, _and_ it doesn't work in C. C++ is just
```scheme
; inherits: c

(lambda_expression
  body: (_) @function.inner) @function.outer

(class_specifier
  body: (_) @class.inner) @class.outer
```
