### ISSUE TITLE
Release for MELPA Stable

### ISSUE THREAD

**Issue by denisw** [meain/evil-textobj-tree-sitter#116]
I have recently switched my Emacs setup from MELPA to [MELPA Stable](https://github.com/melpa/melpa?tab=readme-ov-file#melpa-stable), but noticed that this package is currently not available there. It would be great if I could keep it! 🙂

From what I understand, all that would be required is to tag a release, which MELPA Stable would then pick up for publishing.

**Comment by meain** [comment]
Ahh, tagging a release should be simple enough. I'm wrapping up some query updates for #117 . Will tag a release as soon as that is taken care of.

**Comment by meain** [comment]
FYI, melpa stable is not suggested by package maintainers ([melpa/melpa#3306](https://github.com/melpa/melpa/issues/3306)), but let me add a tag as that does not cost me anything :D

**Comment by meain** [comment]
Added https://github.com/meain/evil-textobj-tree-sitter/releases/tag/0.3

**Comment by denisw** [comment]
Thanks a lot! I‘m aware of the discussion around the usefulness of MELPA Stable, but I‘m currently trying it out anyway. Let‘s see how it goes. 🙂
