### ISSUE TITLE
get listp error with js file

### ISSUE THREAD

**Issue by yqrashawn** [meain/evil-textobj-tree-sitter#15]
the error lies at https://github.com/meain/evil-textobj-tree-sitter/blob/a315a8832fc170c163be01c31b625b19641ce20a/evil-textobj-tree-sitter.el#L111

`first-line-matches` is 0
`(thing-at-point 'line t)` is 
```
"; inherits: (jsx)
"
```

any idea how to fix this?

**Comment by yqrashawn** [comment]
is it because there's no jsx folder in the nvim repo https://github.com/nvim-treesitter/nvim-treesitter-textobjects/tree/master/queries

**Comment by meain** [comment]
Woops, this actually seems like a bug I introduced recently. For some reason, I just assumed that `string-match` did the same thing as `s-match`. Let me take care of that.

Thanks for reporting this.

**Comment by meain** [comment]
This should now be fixed with https://github.com/meain/evil-textobj-tree-sitter/commit/bad7f8d53ecaed5ed6dde8278ed7a02bbee4049f

**Comment by meain** [comment]
I am closing the issue as this should be fixed now. Feel free to reopen if you are still having issues.
