### ISSUE TITLE
changing the name to `evil-textobj-tree-sitter`?

### ISSUE THREAD

**Issue by iyefrat** [meain/evil-textobj-tree-sitter#3]
Hey!
What are your thoughts of changing the package name to `evil-textobj-tree-sitter`? The library is spelled with a hyphen [upstream](https://tree-sitter.github.io/tree-sitter/), as well as in the [emacs implementation and bindings](https://github.com/emacs-tree-sitter). I know it's kind of a hassle, but if this is something you're interested in doing then it's less of a hassle the earlier you do it.
Thanks!

**Comment by meain** [comment]
Yeah, now that I think about it, it should have been `tree-sitter` but I'm not sure if the mess created by changing the name would be worth it.

**Comment by iyefrat** [comment]
Personally I would. The package is new enough that it won't be that much of a mess. Renamed repos redirect from the old url as long as you don't create another repo with the old name, so existing links to the repo won't break. If you rename in two steps (renaming the main .el file in one commit, and renaming all the functions in another), you can keep the git history. The only thing remaining after that is changing the melpa recipe but that's like a few days of inconvenience for people tops, and there are plenty of examples of people doing that in the past.

**Comment by meain** [comment]
The more I look into it, the more I feel like this should have been `tree-sitter`. I think I will go ahed with the change. Everything else that depends on tree sitter is named with `tree-sitter` on melpa.

One concern that I have was breaking configs because of the function name change, but I think I will redirect the arguments to the actual function if called with the old one with deprecation warnings for now.

**Comment by meain** [comment]
I was just playing around with making the change and looks like `use-package` will run into trouble if the thing that we `provide` and the package name are different, or so I think. This would mean that the transition will be much more jarring than I thought and it will break the config for anyone who is using it.

Just wanted to check with you in case you had any input on this?

*The changes I have made so far are available in [rename](https://github.com/meain/evil-textobj-treesitter/tree/rename) branch.*

**Comment by iyefrat** [comment]
> I was just playing around with making the change and looks like use-package will run into trouble if the thing that we provide and the package name are different, or so I think. This would mean that the transition will be much more jarring than I thought and it will break the config for anyone who is using it. 

Yeah, but even if it didn't you'd want to change it anyway, otherwise you're stuck with an odd discrepancy forever. I think you can avoid this by changing the name in melpa first. That way when people update their packages, `evil-textobj-treesitter` will deadend instead of breaking. You can also temporarily generate a warning to users on load that tells them about the name change (before the switch), since that is most of the problem (the fix is dead simple, the issue is understanding that the package changed it's name). 

Then the second the melpa change goes through you can push the rename to the main branch and you're good to go.

All and all even though breaking users' configs sucks, the package is still in it's early days so I don't think it's that big of a deal. You can also temporarily add a Breaking News section to the top of the readme so if people are confused and go to the repo it's the first thing they see.

> The changes I have made so far are available in rename branch.

I checked it out, and installed the package. looks good to me.

**Comment by meain** [comment]
Name change is mostly complete. Just waiting on https://github.com/melpa/melpa/pull/7698 to be merged.

**Comment by meain** [comment]
The package is now officially `evil-textobj-tree-sitter`. Hopefully it is going to be smooth transition for everyone using the package.
