### ISSUE TITLE
Create text object bindings only for treesitter mode

### ISSUE THREAD

**Issue by meliache** [meain/evil-textobj-tree-sitter#5]
I have a conflict for the `f` textobject: In emacs lisp, I want to use the function textobject [provided by lispyville](https://github.com/noctuid/lispyville#text-objects-key-theme), since there is no tree-sitter support for emacs lisp yet. On the other hand, in other programming modes like python, I still want to use the treesitter text objects.

Is there a way I can add these text objects only for tree-sitter mode? Maybe somehow adding them in a buffer local way and use hooks. I guess it's non-trivial because `evil-inner-textobj-map`/`evil-outer-textobj-map` are global and not buffer-local. Maybe it would be possible to have a custom `evil-treesitter-inner-textobject-map` that extends the non-treesitter equivalent, which can be enabled/disabled via a minor mode? I'm not super experience with emacs lisp either, but this is my guess how this could be done.

Actually, this also seems to be an issue on the lispyville side, since they also set their textobjects globally. I found they have even [a TODO](https://github.com/noctuid/lispyville/blob/master/lispyville.el#L2036) in their code, but found no corresponding issue, so I just now also created an issue [over there](https://github.com/noctuid/lispyville/issues/298).

**Comment by meain** [comment]
Since this package does not bind anything by default, I think you should be able to have the evil bind create a function and only call this package's function if tree sitter mode is active. Even though lispyville does bind the items, I think you should be able to rebind it afterwords to call you function and pass the args over to the proper function based on if `tree-sitter` mode is active. I have not been able to give a shot and try if it works for sure, but that is what I think we could do.

**Comment by meliache** [comment]
It's true that you don't bind anything by default, which is why I don't regard this issue as a bugfix report. But I think we could add some configuration hints to the readme and maybe there will be an easier way to toggle treesitter text objects.

In the [lispyville issue](https://github.com/noctuid/lispyville/issues/298#issuecomment-904639071), @noctuid gives a similar recommendation to yours:
> The workaround for now would be to bind the keys yourself to a menu item that selects a different text object depending on whether lispyville-mode is enabled. You can use general-predicate-dispatch to simplify this (it is a small macro you can copy if you do not use general.el).

They also write that they will try using an approach with a specific keymap
> I will continue looking. Maybe I could create a `lispyville-inner-text-objects-map`, for example, that inherits from `evil-inner-text-objects-map` and bind that in `'operator lispyville-mode-map`. I will try that and see if it works.

If that works, I might consider such an approach to configure `evil-textobj-tree-sitter` as well and might do a PR if that works well :)
