### ISSUE TITLE
Invalid Query for Java

### ISSUE THREAD

**Issue by 505aaron** [meain/evil-textobj-tree-sitter#54]
I am seeing the following error:

```
tsc-make-query: Query contains invalid node type: "line_comment", (66 . 3), 1504
```

It looks like changing this:
https://github.com/meain/evil-textobj-tree-sitter/blob/master/queries/java/textobjects.scm#L65-L68

to this works:
```
(comment) @comment.outer
```

I don't have full context here, otherwise I would change it myself.

**Comment by meain** [comment]
The issue is that `line_comment` is a new addition to the java grammar and is not currently available in [emacs-tree-sitter/tree-sitter-langs](https://github.com/emacs-tree-sitter/tree-sitter-langs). I have opened a pr at https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/110 to fix this.

**Comment by 505aaron** [comment]
Thank you @meain

**Comment by meain** [comment]
This should now be fixed upstream.
