### ISSUE TITLE
Add support for bulitin tree-sitter along with elisp-tree-sitter

### ISSUE THREAD

**Issue by meain** [meain/evil-textobj-tree-sitter#76]
Now that tree-sitter is will be [lading in Emacs 29 soon](https://yhetil.org/emacs-devel/83pmd6nbo3.fsf@gnu.org/T/#t),  we should start adding support for that too along with elisp-tree-sitter.

**Comment by d1egoaz** [comment]
This will be great!

**Comment by meain** [comment]
Related(just adding for context): https://lists.gnu.org/archive/html/emacs-devel/2023-03/msg00500.html

**Comment by meain** [comment]
Another possibility is to switch to using textobjects from helix. While they are less fancier, they should be simple and also help with issues like https://github.com/meain/evil-textobj-tree-sitter/issues/88 .

**Comment by meain** [comment]
We now have an experiemtnal version using builtin treesit in https://github.com/meain/evil-textobj-tree-sitter/pull/93 . I hope to dogfood it for a while before merging it.

**Comment by ezmiller** [comment]
Does this package currently not work with the built-in verison of tree-sitter? When I load the package, I do not see any of the `evil-textobj..` functions.

**Comment by meain** [comment]
`treesit` support is still WIP in https://github.com/meain/evil-textobj-tree-sitter/issues/76#issuecomment-1556091358 . That said, you should be seeing most `evil-textobj..` functions without it(although they might not work with builtin treesit).

**Comment by meain** [comment]
This is now available in master.
