### ISSUE TITLE
Add support for additional queries locations

### ISSUE THREAD

**Issue by haikyuu** [meain/evil-textobj-tree-sitter#83]
### Problem statement
When working on a tree-sitter grammar locally, I need to add the query file to the `tree-sitter-langs` folder. And I need to make sure I do that again when I upgrade the package or something.

### Suggested solution
Just like `tree-sitter-load-path ` which is a list of directories to search for shared libraries that define languages, I suggest adding an `evil-textobj-tree-sitter-load-path` list to search for queries in.
Something like this would probably do.
```
(full-path (seq-some (lambda (base-name)
                               (locate-file base-name
                                            tree-sitter-load-path
                                            tree-sitter-load-suffixes))
                             files))
```

**Comment by meain** [comment]
Hmm, this could be useful. Just trying to understand the usecase of this. If these are queries that could be used upstream, feel free to upstream it. But, if you just want to hack on it, I would just suggesting cloning it somewhere and using it from the cloned version. This way you can manage update as well.

Something like the following for `use-package` might come in handy if you decide to use from a local path.
``` emacs-lisp
(use-package evil-textobj-tree-sitter
  :load-path "/path/to/evil-textobj-tree-sitter/")
```

And if they are one off queries, you can use them as you have done in https://github.com/meain/evil-textobj-tree-sitter/issues/84#issue-1585648997 , but you knew that already.

If we decide to do this, we have to decide if we let users pass in a file for each grammar, or just a directory with a similar folder structure as we have currently(any new languages will still need edit in the `evil-textobj-tree-sitter-major-mode-language-alist` variable). If we have multiple files, do both get merged or the user specified one overrides the builtin one.

**Comment by haikyuu** [comment]
I see the main use case for grammar authors (like me) who are iterating on the grammar and the queries on their local machine.
I'm currently using a fork and it's working just fine :) 

> If we decide to do this, we have to decide if we let users pass in a file for each grammar, or just a directory with a similar folder structure as we have currently(any new languages will still need edit in the evil-textobj-tree-sitter-major-mode-language-alist variable). If we have multiple files, do both get merged or the user specified one overrides the builtin one.

It seems like a lot of decisions to be made. Maybe adding a portion of documentation for grammar authors to fork the repo and add their queries is more than enough. 
In my opinion, that's a better option.

**Comment by meain** [comment]
> It seems like a lot of decisions to be made. Maybe adding a portion of documentation for grammar authors to fork the repo and add their queries is more than enough.
In my opinion, that's a better option.

I was thinking the same thing. Sounds good :D

**Comment by meain** [comment]
Add a small note in https://github.com/meain/evil-textobj-tree-sitter/commit/71d9e288a89f254f9041c1781403316c0d21da51
